### ISSUE TITLE
MVF2Fasta issue

### ISSUE THREAD

**Issue by XuexueLiu** [peaselab/mvftools#1]
Dear James,
Today i use mvftools to transform mvf to fasta, but got the error message below. Could you help me to solve it?
thankyou so much!

python mvftools.py ConvertMVF2Fasta --mvf test/test.mvf --out 1
0.02: Regions determined. Reading entries.
Traceback (most recent call last):
  File "mvftools.py", line 1195, in <module>
    MVFcall(time0=TIME0)
  File "mvftools.py", line 119, in __init__
    getattr(self, args.command)()
  File "mvftools.py", line 487, in ConvertMVF2Fasta
    mvf2fasta(args)
  File "/disk/software/mvftools-main/pylib/mvffasphy.py", line 194, in mvf2fasta
    buff = filehandler.read(args.buffer)
  File "/disk/anaconda3/lib/python3.8/tempfile.py", line 474, in func_wrapper
    return func(*args, **kwargs)
io.UnsupportedOperation: not readable

**Comment by jbpease** [comment]
Did you use Python3?  Looks like an io library error.
